# Fundamentos practicos de machine learning

### prueba 1

In [15]:
# Importamos los modulos necesarios
import numpy as np

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [275]:
# cargamos los datos
df = pd.read_csv("salarios_dc1975e5-393f-4b89-9b04-a2b48ce17388.csv")
df.shape, df.columns

((30, 2), Index(['Aexperiencia', 'Salario'], dtype='object'))

In [276]:
# Elegimos nuestras variables X e Y
# Es importante usar esta notacion para tomar solo los valores
x = df.iloc[:,:-1].values
y = df.iloc[:,1:].values

In [277]:
X_train, X_test, Y_train, Y_test =train_test_split(x,y, test_size=0.2, random_state=0)

In [278]:
# es todo el modelo
reg_lin= LinearRegression()
reg_lin.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [279]:
# vemos que dimension es lo que entra al predict
print(X_test.shape)
# creamos un array con lo que quiero probar debe ser de igual dimension
probar = np.array([[5]])
#pruebo el modelo
reg_lin.predict(probar)


(6, 1)


array([[27278.89445395]])

### Prueba con datos 2


In [388]:
#cargo el set
df = pd.read_csv("compensacion-ejecutivos.csv", sep=";")
df.shape, df.columns
df

salario  noasiat   gpa  postgrad  experien
0      99026        0  3,36         0        15
1      69190        1  2,35         1         9
2      95453        1  3,33         1        10
3      57695        1  3,37         0         2
4      94364        1  3,87         1         4
..       ...      ...   ...       ...       ...
105    80765        1  3,12         1         2
106    77081        0  3,36         0         5
107    60024        0  2,51         1         3
108    71606        1  2,89         0         8
109   108625        1  3,85         1         7

[110 rows x 5 columns]

In [389]:
# Una de mis variables taba mal en sus datos
n = np.array(df["gpa"].iloc[:].values)
n.reshape(-1,1)
n=list(n)
for i in range(len(n)):
    n[i]=n[i].replace(",",".")
    n[i]=float(n[i])

In [390]:
#reemplazo en mi var pero solo se puede ejecutar una vez
df["gpa"]=n
#ahora mi variable esta bien
df["gpa"]

0      3.36
1      2.35
2      3.33
3      3.37
4      3.87
       ... 
105    3.12
106    3.36
107    2.51
108    2.89
109    3.85
Name: gpa, Length: 110, dtype: float64

In [391]:
#defino mis variables
x = df.iloc[:,2:].values
y = df.iloc[:,0].values
# selccionamos nuevas variables para x
x_1 = df.iloc[:,2].values
x_2 = df.iloc[:,4].values
x_3= pd.DataFrame({'x_1':x_1, 'x_2': x_2})
x= x_3.iloc[:,:].values
x

array([[ 3.36, 15.  ],
       [ 2.35,  9.  ],
       [ 3.33, 10.  ],
       [ 3.37,  2.  ],
       [ 3.87,  4.  ],
       [ 3.93, 13.  ],
       [ 2.27, 12.  ],
       [ 3.04, 14.  ],
       [ 3.26,  8.  ],
       [ 2.73,  5.  ],
       [ 3.06,  7.  ],
       [ 2.53, 12.  ],
       [ 2.37,  3.  ],
       [ 4.  ,  8.  ],
       [ 2.53, 14.  ],
       [ 2.87, 15.  ],
       [ 1.86, 17.  ],
       [ 2.71, 15.  ],
       [ 3.38, 11.  ],
       [ 1.94,  6.  ],
       [ 3.28, 13.  ],
       [ 3.75,  7.  ],
       [ 3.07, 17.  ],
       [ 2.79,  2.  ],
       [ 1.93,  8.  ],
       [ 3.1 ,  1.  ],
       [ 3.03, 14.  ],
       [ 2.11, 15.  ],
       [ 2.68,  4.  ],
       [ 2.85, 13.  ],
       [ 3.39, 13.  ],
       [ 2.91, 19.  ],
       [ 2.45,  7.  ],
       [ 4.  ,  6.  ],
       [ 2.61, 16.  ],
       [ 3.03, 19.  ],
       [ 2.35, 11.  ],
       [ 4.  ,  7.  ],
       [ 3.14, 13.  ],
       [ 3.44, 10.  ],
       [ 3.27, 10.  ],
       [ 2.57, 10.  ],
       [ 3.29, 11.  ],
       [ 2.

In [392]:
# hago el entrenamiento 
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.3, random_state=0)

In [393]:
# creo el modelo
reg_lin= LinearRegression()
reg_lin.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [394]:
# reviso que entra a predict
print(X_test.shape)
#creo mi prueba
prueba =np.array([[4.2,3.1 ]])
#COmpruebo que mis dimensiones sean iguales
prueba.shape
#realizo el test
reg_lin.predict(prueba)

(33, 2)


array([96088.13529746])

In [395]:
#probar el model
reg_lin.score(X_test, Y_test)

0.7481197579142014

# Estadistica con python


### prueba 1

In [1]:
#importamos los modelos necesarios 
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics

In [3]:
#cargamos los datos

df = pd.read_csv("felicidad_b0b50c6d-41dd-4ea8-a4f0-92a8068d4d3e.csv")
df.shape, df.columns

((155, 12),
 Index(['country', 'rank', 'score', 'high', 'low', 'gdp', 'family', 'lifexp',
        'freedom', 'generosity', 'corruption', 'dystopia'],
       dtype='object'))

In [6]:
#asignamos variables 

x = df[["gdp", "family", "lifexp", "freedom", "corruption", "generosity", "dystopia"]]
y = df[["score"]] 
    

In [7]:
# Creamos el modelo
reg_lin = sm.OLS(y, sm.add_constant(x) ).fit()

In [8]:
reg_lin.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  score   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.442e+08
Date:                Wed, 12 Feb 2020   Prob (F-statistic):               0.00
Time:                        19:22:34   Log-Likelihood:                 1048.9
No. Observations:                 155   AIC:                            -2082.
Df Residuals:                     147   BIC:                            -2057.
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0002      0.000      1.171      0.243      -0.000       0.000
gdp            1.0001      0.000   8513.538      0.000       1.000       1.000
family         0.9999      0.000   8637.659      0.000       1.000       1.000
lifexp         0.9999      0.000   5419.877      0.000       1.000       1.000
freedom        1.0000      0.000   5069.249      0.000       1.000       1.000
corruption     0.9998      0.000   3605.631      0.000       0.999       1.000
generosity     1.0002      0.000   5245.012      0.000       1.000       1.001
dystopia       1.0000    4.7e-05   2.13e+04      0.000       1.000       1.000
==============================================================================
Omnibus:                       49.955   Durbin-Watson:                   2.035
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                8.708
Skew:                          -0.079   Prob(JB):                       0.0129
Kurtosis:                       1.850   Cond. No.                         35.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [401]:
# muestro la dimension de lo que entra a predict
sm.add_constant(x).shape
#creo la nueva matriz a probar
probar = [1,5]
#pruebo el modelo
reg_lin.predict(probar)


array([27517.89696649])

### Prueba 2

In [402]:
import statsmodels.api as sm
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics

In [403]:
# cargo los datos
df = pd.read_csv("compensacion-ejecutivos.csv", sep=";")
df.shape, df.columns

((110, 5),
 Index(['salario', 'noasiat', 'gpa', 'postgrad', 'experien'], dtype='object'))

In [404]:

n = np.array(df["gpa"].iloc[:].values)
n.reshape(-1,1)
n=list(n)
for i in range(len(n)):
    n[i]=n[i].replace(",",".")
    n[i]=float(n[i])
df["gpa"]=n

In [405]:
#seleccion de variables 
y = df["salario"]
x = df.drop(['salario', 'noasiat',  'postgrad', ],axis =1)

In [406]:
# creo el modelo
reg_lin = sm.OLS(y, sm.add_constant(x) ).fit()

In [408]:
#dimensiones
sm.add_constant(x).shape
# pruebo el modelo
reg_lin.predict([1,4.2,3.1 ])

array([96074.05771139])

# Introduccion a machine learning

### Prueba 1

In [470]:
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np


In [494]:
#cargamos los datos y trasnformamos de pandas a array a torch
df = pd.read_csv("salarios_dc1975e5-393f-4b89-9b04-a2b48ce17388.csv")

df.values


array([[1.0000e+01, 4.2500e+04],
       [8.0000e+00, 3.6302e+04],
       [5.4000e+00, 3.5000e+04],
       [2.5000e+00, 1.8103e+04],
       [1.0000e+00, 1.5000e+04],
       [8.0000e+00, 3.7000e+04],
       [4.0000e+00, 2.6300e+04],
       [6.0000e+00, 3.5201e+04],
       [2.0000e+00, 1.8302e+04],
       [1.0000e+01, 4.2000e+04],
       [4.0000e+00, 2.7000e+04],
       [7.0000e+00, 3.5201e+04],
       [3.0000e+00, 1.9201e+04],
       [5.0000e+00, 2.8000e+04],
       [2.0000e+00, 1.7000e+04],
       [5.0000e+00, 3.3402e+04],
       [3.0000e+00, 1.9000e+04],
       [2.0000e+00, 1.8200e+04],
       [3.0000e+00, 1.9000e+04],
       [2.0000e+00, 1.7301e+04],
       [5.0000e+00, 2.8000e+04],
       [3.4000e+00, 2.0000e+04],
       [5.3000e+00, 2.7900e+04],
       [2.1000e+00, 1.7500e+04],
       [9.2000e+00, 4.0000e+04],
       [1.0000e+01, 4.2500e+04],
       [3.2000e+00, 1.8300e+04],
       [1.0000e+01, 4.0000e+04],
       [4.0000e+00, 2.5000e+04],
       [1.0000e+00, 1.5000e+04]])

In [489]:
#asignamos las variables
x= df["Aexperiencia"].iloc[:].ca
y= df["Salario"].iloc[:].values
y

AttributeError: 'Series' object has no attribute 'ca'