In [12]:
import numpy as np
import pandas as pd

In [13]:
def iterar(columna,fila,data):
    cantidad_de_filas, cantidad_de_columnas = filas_y_columnas(data)
    data[fila] = data[fila]/data[fila][columna]
    for i in range(cantidad_de_filas):
        if i == fila:
            continue
        data[i]=data[i]+(data[fila]*-data[i][columna])
    print(data)
    estoy_en_el_optimo(data)
    
    

In [14]:
def crear_dataFrame(columna,fila, data):
    nombre_de_fila=[]
    nombre_de_columna=[]
    for i in range(columna):
        nombre = input(f"inserte el nombre de la columna {i}: ")
        nombre_de_columna.append(nombre)
    for i in range(fila):
        nombre = input(f"inserte el nombre de la fila {i}: ")
        nombre_de_fila.append(nombre)
    df = pd.DataFrame(data, columns=nombre_de_columna, index=nombre_de_fila)
    return df

In [15]:
def filas_y_columnas(data):
    return data.shape[0], data.shape[1]

In [16]:
def estoy_en_el_optimo(data):
    neg=0
    for i in range(data.shape[1]):
        try:
            if data[0][i] <0 : 
                neg=+1
        except TypeError as e:
            print("no se leer la m")
    if neg == 0:
        print("Has optimizado la funcion")
    else:
        print("Aun no estas en el optimo, vuleve a iterar")
        

In [33]:
tabla_1 = np.array([[1,-7,-4,0,0,0,0],[0,2,1,1,0,0,20],[0,1,1,0,1,0,18],[0,1,0,0,0,1,8]])
tabla_1


array([[ 1, -7, -4,  0,  0,  0,  0],
       [ 0,  2,  1,  1,  0,  0, 20],
       [ 0,  1,  1,  0,  1,  0, 18],
       [ 0,  1,  0,  0,  0,  1,  8]])

In [34]:
iterar(1,3, tabla_1)

[[ 1  0 -4  0  0  7 56]
 [ 0  0  1  1  0 -2  4]
 [ 0  0  1  0  1 -1 10]
 [ 0  1  0  0  0  1  8]]
estamos evaluando el valor:  1
estamos evaluando el valor:  0
estamos evaluando el valor:  -4
el valor del contador es:  1
estamos evaluando el valor:  0
estamos evaluando el valor:  0
estamos evaluando el valor:  7
estamos evaluando el valor:  56
Aun no estas en el optimo, vuleve a iterar


In [35]:
iterar(2,1,tabla_1)

[[ 1  0  0  4  0 -1 72]
 [ 0  0  1  1  0 -2  4]
 [ 0  0  0 -1  1  1  6]
 [ 0  1  0  0  0  1  8]]
estamos evaluando el valor:  1
estamos evaluando el valor:  0
estamos evaluando el valor:  0
estamos evaluando el valor:  4
estamos evaluando el valor:  0
estamos evaluando el valor:  -1
el valor del contador es:  1
estamos evaluando el valor:  72
Aun no estas en el optimo, vuleve a iterar


In [36]:
iterar(5,2,tabla_1)

[[ 1  0  0  3  1  0 78]
 [ 0  0  1 -1  2  0 16]
 [ 0  0  0 -1  1  1  6]
 [ 0  1  0  1 -1  0  2]]
estamos evaluando el valor:  1
estamos evaluando el valor:  0
estamos evaluando el valor:  0
estamos evaluando el valor:  3
estamos evaluando el valor:  1
estamos evaluando el valor:  0
estamos evaluando el valor:  78
Has optimizado la funcion


In [37]:
    
nombres =["Z", "X1", "x2", "S1", "S2","S3","Resultado"]
indice=["Z","X2","S3", "X1"]

df =pd.DataFrame(data = tabla_1, columns=nombres, index=indice)
df

Z  X1  x2  S1  S2  S3  Resultado
Z   1   0   0   3   1   0         78
X2  0   0   1  -1   2   0         16
S3  0   0   0  -1   1   1          6
X1  0   1   0   1  -1   0          2

In [38]:
for i in range(df.shape[0]):
    var = df.index[i]
    resultado= df.iloc[i,6]
    print(f"El resultado de {var} es: {resultado}")

El resultado de Z es: 78
El resultado de X2 es: 16
El resultado de S3 es: 6
El resultado de X1 es: 2


### Tabla 2

In [6]:
from sympy import *

In [7]:
M = Symbol("M")

In [25]:


tabla_2 = np.array([[1,-5,-4,0,0,0,M,0],[0,2,1,1,0,0,0,20],[0,1,1,0,1,0,0,18],[0,1,2,0,0,-1,1,12]])
tabla_2

array([[1, -5, -4, 0, 0, 0, M, 0],
       [0, 2, 1, 1, 0, 0, 0, 20],
       [0, 1, 1, 0, 1, 0, 0, 18],
       [0, 1, 2, 0, 0, -1, 1, 12]], dtype=object)

In [26]:
iterar(6,3,tabla_2)

[[1 -1.0*M - 5 -2.0*M - 4 0 0 1.0*M 0 -12.0*M]
 [0.0 2.0 1.0 1.0 0.0 0.0 0.0 20.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 18.0]
 [0.0 1.0 2.0 0.0 0.0 -1.0 1.0 12.0]]
no se leer la m
no se leer la m
no se leer la m
no se leer la m
Has optimizado la funcion


In [27]:
iterar(2,3,tabla_2)

[[1 -3.00000000000000 0 0 0 -2.00000000000000 1.0*M + 2.0
  24.0000000000000]
 [0.0 1.5 0.0 1.0 0.0 0.5 -0.5 14.0]
 [0.0 0.5 0.0 0.0 1.0 0.5 -0.5 12.0]
 [0.0 0.5 1.0 0.0 0.0 -0.5 0.5 6.0]]
no se leer la m
Aun no estas en el optimo, vuleve a iterar


In [28]:
 iterar(1,1,tabla_2)

[[1 0 0 2.00000000000000 0 -1.00000000000000 1.0*M + 1.0 52.0000000000000]
 [0.0 1.0 0.0 0.6666666666666666 0.0 0.3333333333333333
  -0.3333333333333333 9.333333333333334]
 [0.0 0.0 0.0 -0.3333333333333333 1.0 0.33333333333333337
  -0.33333333333333337 7.333333333333333]
 [0.0 0.0 1.0 -0.3333333333333333 0.0 -0.6666666666666666
  0.6666666666666666 1.333333333333333]]
no se leer la m
Aun no estas en el optimo, vuleve a iterar


In [41]:
iterar(5,2,tabla_2)
tabla_2[0][6] = 9999
tabla_2.astype(float)

[[1 0 0 1.00000000000000 3.00000000000000 0 9999 74.0000000000000]
 [0.0 1.0 0.0 0.9999999999999999 -0.9999999999999998 0.0 0.0
  2.0000000000000018]
 [0.0 0.0 0.0 -0.9999999999999999 2.9999999999999996 1.0 -1.0
  21.999999999999996]
 [0.0 0.0 1.0 -0.9999999999999998 1.9999999999999996 0.0 0.0
  15.999999999999996]]
Has optimizado la funcion


array([[1.0, 0.0, 0.0, 1.0, 3.0, 0.0, 9999.0, 74.0],
       [0.0, 1.0, 0.0, 1.0, -1.0, 0.0, 0.0, 2.0],
       [0.0, 0.0, 0.0, -1.0, 3.0, 1.0, -1.0, 22.0],
       [0.0, 0.0, 1.0, -1.0, 2.0, 0.0, 0.0, 16.0]])

In [32]:
np.set_printoptions(formatter={"float": lambda x:"%0.1f"%(x)})

In [260]:
tabla_2 =tabla_2.reshape(-1)

In [310]:
tabla_2=tabla_2.reshape(-1)
lista_1 =list(tabla_2)
lista_1

[1,
 0,
 0,
 1.0,
 3.0,
 0,
 1.0*M,
 74.0000000000000,
 0.0,
 1.0,
 0.0,
 1.0,
 -0.9999999999999998,
 0.0,
 0.0,
 2.0000000000000018,
 0.0,
 0.0,
 0.0,
 -0.9999999999999999,
 2.9999999999999996,
 1.0,
 -1.0,
 21.999999999999996,
 0.0,
 0.0,
 1.0,
 -0.9999999999999998,
 1.9999999999999996,
 0.0,
 0.0,
 15.999999999999996]